// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pratico.Data.Context;

namespace Pratico.Data.Migrations
{
    [DbContext(typeof(PraticoContext))]
    [Migration("20230117054507_novaTabelaUsuarioCondominio2")]
    partial class novaTabelaUsuarioCondominio2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Pratico.Dominio.Model.Andar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Conjuntoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short>("NumAndarInterno")
                        .HasColumnType("smallint");

                    b.Property<short>("NumTorre")
                        .HasColumnType("smallint");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Conjuntoid");

                    b.ToTable("Andar");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<int>("CodCondominio")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<short>("DiaVencimento")
                        .HasColumnType("smallint");

                    b.Property<short>("Finalidade")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Fracao")
                        .HasColumnType("decimal");

                    b.Property<string>("InscEstadual")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscMunicipal")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("RepresentanteLegalId")
                        .HasColumnType("uuid");

                    b.Property<short>("TipoCondominio")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepresentanteLegalId");

                    b.ToTable("Condominio");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Conjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("Conjunto");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<short>("Ddd")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("Entidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.DocumentoImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid>("ImovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<string>("NomeDoc")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TipoDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("varchar(200)");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.ToTable("DocumentoImovel");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Cep")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Cobranca")
                        .HasColumnType("boolean");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid>("Entidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Referencia")
                        .HasColumnType("varchar(200)");

                    b.Property<short>("UF")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.GerenciamentoDocImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<bool>("DocEnviado")
                        .HasColumnType("boolean");

                    b.Property<bool>("DocValidado")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailEnviado")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailLido")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ImovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId")
                        .IsUnique();

                    b.ToTable("GerenciamentoDocImovel");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AndarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid");

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric");

                    b.Property<short>("Conjunto")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Fracao")
                        .HasColumnType("numeric");

                    b.Property<short>("NumAndar")
                        .HasColumnType("smallint");

                    b.Property<string>("NumImovel")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("NumImovelinterno")
                        .HasColumnType("integer");

                    b.Property<Guid?>("Proprietario")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AndarId");

                    b.ToTable("Imovel");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.InquilinoImovel", b =>
                {
                    b.Property<Guid>("ImovelId")
                        .HasColumnName("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PessoaId")
                        .HasColumnName("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.HasKey("ImovelId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("InquilinoImovel");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.MoradorImovel", b =>
                {
                    b.Property<Guid>("ImovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ImovelId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<Guid>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PessoaId")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.HasKey("ImovelId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("MoradorImovel");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnh")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("Timestamp(0)");

                    b.Property<short>("EstadoCivil")
                        .HasColumnType("smallint");

                    b.Property<string>("InscEstadual")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscMunicipal")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rg")
                        .HasColumnType("varchar(100)");

                    b.Property<short>("Sexo")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoDocumento")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoPessoa")
                        .HasColumnType("smallint");

                    b.Property<bool>("UsarEndImovel")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ProprietarioImovel", b =>
                {
                    b.Property<Guid>("ImovelId")
                        .HasColumnName("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PessoaId")
                        .HasColumnName("PessoaId")
                        .HasColumnType("uuid");

                    b.HasKey("ImovelId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("ProprietarioImovel");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.RepresentanteLegal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AssinaDoc")
                        .HasColumnType("boolean");

                    b.Property<short>("Cargo")
                        .HasColumnType("smallint");

                    b.Property<string>("CnpjRep")
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataNascimentoRep")
                        .HasColumnType("Timestamp(0)");

                    b.Property<short>("EstCivil")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FimPeriodo")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("IniPeriodo")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("InscEstadualRep")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscMunicipalRep")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NomeFantasiaRep")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeRep")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumDoc")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RazaoSocialRep")
                        .HasColumnType("varchar(200)");

                    b.Property<short>("Sexo")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoDoc")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("RepresentanteLegal");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<short>("TipoUsuario")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.UsuarioCondominio", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CondominioId");

                    b.ToTable("UsuarioCondominio");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Andar", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Conjunto", "Conjunto")
                        .WithMany("Andares")
                        .HasForeignKey("Conjuntoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Condominio", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.RepresentanteLegal", null)
                        .WithMany("Condominios")
                        .HasForeignKey("RepresentanteLegalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Conjunto", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany("Conjuntos")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.DocumentoImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", null)
                        .WithMany("Documentos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.GerenciamentoDocImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", "Imovel")
                        .WithOne("DocImovel")
                        .HasForeignKey("Pratico.Dominio.Model.GerenciamentoDocImovel", "ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Imovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Andar", "Andar")
                        .WithMany("Imoveis")
                        .HasForeignKey("AndarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.InquilinoImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", "Imovel")
                        .WithMany("InquilinosImovel")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany("InquilinosImovel")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.MoradorImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", "Imovel")
                        .WithMany("MoradoresImovel")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany("MoradoresImovel")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ProprietarioImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", "Imovel")
                        .WithMany("ProprietariosImovel")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany("ProprietariosImovel")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.UsuarioCondominio", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany("UsuarioCondominio")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
