// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pratico.Data.Context;

#nullable disable

namespace Pratico.Data.Migrations
{
    [DbContext(typeof(PraticoContext))]
    [Migration("20260724040429_AddOutBoxMessage")]
    partial class AddOutBoxMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pratico.Dominio.Model.AcessoVisitante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AndarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<Guid>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<Guid>("ConjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid>("ImovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<string>("NomeVisitante")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumDoc")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<short>("TipoDocumento")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("AcessoVisitante", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.AgendaAreaLazer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaLazerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<short>("Autorizado")
                        .HasColumnType("smallint");

                    b.Property<Guid>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.HasKey("Id");

                    b.HasIndex("AreaLazerId");

                    b.HasIndex("CondominioId");

                    b.HasIndex("PessoaId");

                    b.ToTable("AgendaAreaLazer", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Andar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("NumAndarInterno")
                        .HasColumnType("smallint");

                    b.Property<short>("NumTorre")
                        .HasColumnType("smallint");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConjuntoId");

                    b.ToTable("Andar", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.AreaLazer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Capacidade")
                        .HasColumnType("smallint");

                    b.Property<Guid>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("AreaLazer", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<int>("CodCondominio")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<short>("DiaVencimento")
                        .HasColumnType("smallint");

                    b.Property<short>("Finalidade")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Fracao")
                        .HasColumnType("decimal");

                    b.Property<string>("InscEstadual")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscMunicipal")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("RepresentanteLegalId")
                        .HasColumnType("uuid");

                    b.Property<short>("TipoCondominio")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepresentanteLegalId");

                    b.ToTable("Condominio", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Conjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("Conjunto", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<short>("Ddd")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("Entidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Contato", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ConvidadoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataChegada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("Timestamp(0)");

                    b.Property<Guid>("ListaEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<Guid>("MoradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeAnfitriao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumDoc")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<short>("TipoDoc")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ListaEventoId");

                    b.ToTable("ConvidadoEvento", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Codigo")
                        .HasColumnType("smallint");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("Departamento", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.DocumentoImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid>("ImovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<string>("NomeDoc")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TipoDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("varchar(200)");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.ToTable("DocumentoImovel", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.EmpresaSimplificada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("Operador")
                        .HasColumnType("uuid");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("EmpresaSimplificada", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Cep")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Cobranca")
                        .HasColumnType("boolean");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid>("Entidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Referencia")
                        .HasColumnType("varchar(200)");

                    b.Property<short>("UF")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Endereco", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.FilaEspera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgendaAreaLazerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.HasKey("Id");

                    b.ToTable("FilaEspera", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.GerenciamentoDocImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<bool>("DocEnviado")
                        .HasColumnType("boolean");

                    b.Property<bool>("DocValidado")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailEnviado")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailLido")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ImovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId")
                        .IsUnique();

                    b.ToTable("GerenciamentoDocImovel", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AndarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid");

                    b.Property<decimal>("Area")
                        .HasColumnType("numeric");

                    b.Property<short>("Conjunto")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fracao")
                        .HasColumnType("numeric");

                    b.Property<short>("NumAndar")
                        .HasColumnType("smallint");

                    b.Property<string>("NumImovel")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("NumImovelinterno")
                        .HasColumnType("integer");

                    b.Property<Guid?>("Proprietario")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AndarId");

                    b.ToTable("Imovel", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.InquilinoImovel", b =>
                {
                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("ImovelId");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("PessoaId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.HasKey("ImovelId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("InquilinoImovel", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ItemRemessaInterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeRetirante")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("Operador")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RemessaInternaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rg")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TipoDocumentoEntregaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Vendedor")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RemessaInternaId");

                    b.HasIndex("TipoDocumentoEntregaId");

                    b.ToTable("ItemRemessaInterna", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ListaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgendaAreaLazerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("NomeArea")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("varchar(50)");

                    b.Property<string>("NomeDonoEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AgendaAreaLazerId");

                    b.ToTable("ListaEvento", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.MoradorImovel", b =>
                {
                    b.Property<Guid>("ImovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ImovelId")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<Guid>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PessoaId")
                        .HasDefaultValueSql("'uuid'");

                    b.HasKey("ImovelId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("MoradorImovel", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Operador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rg")
                        .HasColumnType("varchar(20)");

                    b.Property<short>("Sexo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("Operador", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.OutBoxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime?>("DataUltimaTentativa")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Erro")
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("ProximaTentativaEm")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pendente");

                    b.Property<int>("Tentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ProximaTentativaEm");

                    b.ToTable("OutBox", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnh")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("Timestamp(0)");

                    b.Property<short>("EstadoCivil")
                        .HasColumnType("smallint");

                    b.Property<string>("InscEstadual")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscMunicipal")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rg")
                        .HasColumnType("varchar(100)");

                    b.Property<short>("Sexo")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoDocumento")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoPessoa")
                        .HasColumnType("smallint");

                    b.Property<bool>("UsarEndImovel")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Pessoa", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.PessoaUsuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId");

                    b.HasIndex("PessoaId");

                    b.ToTable("PessoaUsuario", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ProprietarioImovel", b =>
                {
                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid")
                        .HasColumnName("ImovelId");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("PessoaId");

                    b.Property<bool>("Validado")
                        .HasColumnType("boolean")
                        .HasColumnName("Validado");

                    b.HasKey("ImovelId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("ProprietarioImovel", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.RemessaExterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid>("EmpresaSimplificadaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Interna")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<short>("QuantidadeItens")
                        .HasColumnType("smallint");

                    b.Property<short>("QuantidadeLancados")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.HasIndex("EmpresaSimplificadaId");

                    b.HasIndex("OperadorId");

                    b.ToTable("RemessaExterna", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.RemessaInterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AndarId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoRetirada")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConjuntoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<short>("QuantidadeItens")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AndarId");

                    b.HasIndex("CondominioId");

                    b.HasIndex("ConjuntoId");

                    b.HasIndex("ImovelId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("PessoaId");

                    b.ToTable("RemessaInterna", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.RepresentanteLegal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AssinaDoc")
                        .HasColumnType("boolean");

                    b.Property<short>("Cargo")
                        .HasColumnType("smallint");

                    b.Property<string>("CnpjRep")
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("'uuid'");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("DataNascimentoRep")
                        .HasColumnType("Timestamp(0)");

                    b.Property<short>("EstCivil")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("FimPeriodo")
                        .HasColumnType("Timestamp(0)");

                    b.Property<DateTime>("IniPeriodo")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("InscEstadualRep")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscMunicipalRep")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NomeFantasiaRep")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeRep")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumDoc")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RazaoSocialRep")
                        .HasColumnType("varchar(200)");

                    b.Property<short>("Sexo")
                        .HasColumnType("smallint");

                    b.Property<short>("TipoDoc")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("RepresentanteLegal", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.TipoAreaLazer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("TipoAreaLazer", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.TipoDocumentoEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumentoEntrega", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.TipoFormato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Codigo")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoFormato", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.TipoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Codigo")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoItem", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.TipoVolume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Codigo")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoVolume", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<short>("TipoUsuario")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Usuario", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.UsuarioCondominio", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CondominioId");

                    b.ToTable("UsuarioCondominio", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.UsuarioSistema", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CondominioId");

                    b.ToTable("UsuarioSistema", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.VeiculoCor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("VeiculoCor", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.VeiculoFabricante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("VeiculoFabricante", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.VeiculoTipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("VeiculoTipo", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.VendedorRemessa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("Timestamp(0)");

                    b.Property<Guid?>("EmpresaSimplificadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RemessaExternaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaSimplificadaId");

                    b.HasIndex("RemessaExternaId");

                    b.ToTable("VendedorRemessa", "public");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.AcessoVisitante", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany("AcessoVisitantes")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.AgendaAreaLazer", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.AreaLazer", "AreaLazer")
                        .WithMany("Agenda")
                        .HasForeignKey("AreaLazerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany("AgendaAreaLazer")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaLazer");

                    b.Navigation("Condominio");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Andar", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Conjunto", "Conjunto")
                        .WithMany("Andares")
                        .HasForeignKey("ConjuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conjunto");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.AreaLazer", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", null)
                        .WithMany("AreasLazer")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Condominio", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.RepresentanteLegal", null)
                        .WithMany("Condominios")
                        .HasForeignKey("RepresentanteLegalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Conjunto", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany("Conjuntos")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ConvidadoEvento", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.ListaEvento", "ListaEvento")
                        .WithMany("Convidaddos")
                        .HasForeignKey("ListaEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaEvento");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Departamento", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.DocumentoImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", null)
                        .WithMany("Documentos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.EmpresaSimplificada", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany("EmpresaSimplificada")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.GerenciamentoDocImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", "Imovel")
                        .WithOne("DocImovel")
                        .HasForeignKey("Pratico.Dominio.Model.GerenciamentoDocImovel", "ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Imovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Andar", "Andar")
                        .WithMany("Imoveis")
                        .HasForeignKey("AndarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Andar");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.InquilinoImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", "Imovel")
                        .WithMany("InquilinosImovel")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany("InquilinosImovel")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ItemRemessaInterna", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.RemessaInterna", "RemessaInterna")
                        .WithMany("Itens")
                        .HasForeignKey("RemessaInternaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.TipoDocumentoEntrega", "TipoDocumentoEntrega")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemessaInterna");

                    b.Navigation("TipoDocumentoEntrega");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ListaEvento", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.AgendaAreaLazer", "AgendaAreaLazer")
                        .WithMany()
                        .HasForeignKey("AgendaAreaLazerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaAreaLazer");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.MoradorImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", "Imovel")
                        .WithMany("MoradoresImovel")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany("MoradoresImovel")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Operador", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany("Operador")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.PessoaUsuario", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany("PessoaUsuario")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ProprietarioImovel", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Imovel", "Imovel")
                        .WithMany("ProprietariosImovel")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany("ProprietariosImovel")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.RemessaExterna", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany("Remessas")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.EmpresaSimplificada", "EmpresaSimplificada")
                        .WithMany("Remessas")
                        .HasForeignKey("EmpresaSimplificadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Operador", "Operador")
                        .WithMany("RemessaExterna")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Condominio");

                    b.Navigation("EmpresaSimplificada");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.RemessaInterna", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Andar", "Andar")
                        .WithMany()
                        .HasForeignKey("AndarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Conjunto", "Conjunto")
                        .WithMany()
                        .HasForeignKey("ConjuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pratico.Dominio.Model.Operador", "Operador")
                        .WithMany("RemessaInterna")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pratico.Dominio.Model.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Andar");

                    b.Navigation("Condominio");

                    b.Navigation("Conjunto");

                    b.Navigation("Imovel");

                    b.Navigation("Operador");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.TipoAreaLazer", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", null)
                        .WithMany("TiposAreaLazer")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pratico.Dominio.Model.UsuarioCondominio", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany("UsuarioCondominio")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.UsuarioSistema", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.Condominio", "Condominio")
                        .WithMany("UsuarioSistema")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.VendedorRemessa", b =>
                {
                    b.HasOne("Pratico.Dominio.Model.EmpresaSimplificada", "EmpresaSimplificada")
                        .WithMany()
                        .HasForeignKey("EmpresaSimplificadaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pratico.Dominio.Model.RemessaExterna", "RemessaExterna")
                        .WithMany()
                        .HasForeignKey("RemessaExternaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("EmpresaSimplificada");

                    b.Navigation("RemessaExterna");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Andar", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.AreaLazer", b =>
                {
                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Condominio", b =>
                {
                    b.Navigation("AgendaAreaLazer");

                    b.Navigation("AreasLazer");

                    b.Navigation("Conjuntos");

                    b.Navigation("EmpresaSimplificada");

                    b.Navigation("Operador");

                    b.Navigation("Remessas");

                    b.Navigation("TiposAreaLazer");

                    b.Navigation("UsuarioCondominio");

                    b.Navigation("UsuarioSistema");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Conjunto", b =>
                {
                    b.Navigation("Andares");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.EmpresaSimplificada", b =>
                {
                    b.Navigation("Remessas");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Imovel", b =>
                {
                    b.Navigation("DocImovel");

                    b.Navigation("Documentos");

                    b.Navigation("InquilinosImovel");

                    b.Navigation("MoradoresImovel");

                    b.Navigation("ProprietariosImovel");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.ListaEvento", b =>
                {
                    b.Navigation("Convidaddos");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Operador", b =>
                {
                    b.Navigation("RemessaExterna");

                    b.Navigation("RemessaInterna");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.Pessoa", b =>
                {
                    b.Navigation("AcessoVisitantes");

                    b.Navigation("InquilinosImovel");

                    b.Navigation("MoradoresImovel");

                    b.Navigation("PessoaUsuario");

                    b.Navigation("ProprietariosImovel");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.RemessaInterna", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Pratico.Dominio.Model.RepresentanteLegal", b =>
                {
                    b.Navigation("Condominios");
                });
#pragma warning restore 612, 618
        }
    }
}
