<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.2" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.9.18" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.14.1" />
    <PackageReference Include="Comtele.Sdk" Version="1.3.1" />
    <PackageReference Include="MediatR" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="SendGrid" Version="9.28.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pratico.Dominio\Pratico.Dominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Andar\Commands\Update\" />
    <Folder Include="Services\Andar\Queries\" />
    <Folder Include="Services\ConvidadoEvento\Commands\" />
    <Folder Include="Services\ConvidadoEvento\Queries\" />
    <Folder Include="Services\ListaEvento\Commands\Delete\" />
    <Folder Include="Services\ListaEvento\Commands\Update\" />
    <Folder Include="Services\ListaEvento\Queries\" />
  </ItemGroup>

</Project>
